name: build

on:
  push:
    branches:
      - '*'

jobs:
  build-binaries:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
        
      - name: Build
        run: |
          dotnet publish ./src/qest/ -o ./pub --runtime linux-x64 -c Release --self-contained true /p:PublishSingleFile=true
          dotnet publish ./src/qest/ -o ./pub --runtime win-x64 -c Release --self-contained true /p:PublishSingleFile=true

  build-docker-standalone:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: standalone.dockerfile
          pull: true
          push: false
          tags: standalone, standalone-latest, standalone-${{ github.ref_name }}
          
  build-docker-bundle:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: bundle.dockerfile
          pull: true
          push: false
          tags: bundle, bundle-latest, bundle-${{ github.ref_name }}
            
