name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build-binaries:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
        
      - name: Build
        run: |
          dotnet publish ./src/qest/ -o ./pub --runtime linux-x64 -c Release --self-contained true /p:PublishSingleFile=true
          dotnet publish ./src/qest/ -o ./pub --runtime win-x64 -c Release --self-contained true /p:PublishSingleFile=true

  build-docker-standalone:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build Docker standalone image
        with:
          image: qest
          tags: standalone, standalone-latest, standalone-${{ github.ref_name }}
          registry: ghcr.io
          dockerfile: standalone.dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          pushImage: false
  
  build-docker-bundle:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build Docker bundle image
        with:
          image: qest
          tags: bundle, bundle-latest, bundle-${{ github.ref_name }}
          registry: ghcr.io
          dockerfile: bundle.dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          pushImage: false