
name: release

on:
  push:
    tags: 
      - '*'

jobs:
  build-binaries:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 8.x.x
        
      - name: Build
        run: |
          dotnet publish ./src/qest/ -o ./pub --runtime linux-x64 -c Release --self-contained true /p:PublishSingleFile=true
          dotnet publish ./src/qest/ -o ./pub --runtime win-x64 -c Release --self-contained true /p:PublishSingleFile=true
          
      - name: Create Packages
        run: |
          gzip -c ./pub/qest > ./qest-linux-x64.gz
          gzip -c ./pub/qest.exe > ./qest-win-x64.gz
          
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  build-docker-standalone:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker standalone image
        with:
          image: qest
          tags: standalone, standalone-latest, standalone-${{ github.ref_name }}
          registry: ghcr.io
          dockerfile: standalone.dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
  build-docker-bundle:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker bundle image
        with:
          image: qest
          tags: bundle, bundle-latest, bundle-${{ github.ref_name }}
          registry: ghcr.io
          dockerfile: bundle.dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
